### ISSUE TITLE
FavIcon : Add

### ISSUE THREAD

**Issue by CharlotteDeDeyne** [unikbase/website#12]
Add Following FavIcon
![favicon](https://user-images.githubusercontent.com/123545031/215127872-dc09a91b-89ac-486e-94d8-bab0671bbdac.png)
![favicon](https://user-images.githubusercontent.com/123545031/215127876-1f317dfd-28c3-48ae-9965-ce3b294ac8db.svg)

**Comment by rambuvn** [comment]
![image](https://user-images.githubusercontent.com/1720202/215253025-dca826b0-aa64-4d3b-a1af-152fd94837d9.png)
