### ISSUE TITLE
Animated logo

### ISSUE THREAD

**Issue by smichea** [unikbase/website#2]

**Comment by Nicolasunikbase** [comment]
at the top left hand corner of the website, when the site first loads

**Comment by Nicolasunikbase** [comment]
animated logo and animated icons will be ready by Friday (currently developed in the philippines)

**Comment by Nicolasunikbase** [comment]
Hi!
are we making progress on this one?
thanks!

**Comment by smichea** [comment]
where can we find the animated logo ?
