### ISSUE TITLE
Homepage film

### ISSUE THREAD

**Issue by Nicolasunikbase** [unikbase/website#24]
Replace the current opening image (the one with the 5 layers of collectibles) by a film (to be downloaded here : https://f.io/7kxy49gK)
Please refer  to this layout:
<img width="348" alt="Screenshot 2023-02-14 at 16 30 26" src="https://user-images.githubusercontent.com/122465123/218783066-4e77c34c-fea9-4323-82f1-633aade882e3.png">

- video should autoplay as soon as the homepage is loaded
- no loop.
- sound off by default,  pls make the sound on button obvious enough
- for now dimensions are 16/9, please let me know asap if other dimensions are needed

**Comment by ryansagot** [comment]
QA Passed using today's version of the website.

**Comment by ryansagot** [comment]
Reopening this ticket for the following additional changes.
- Please loop the video and remove the timebar / remove the sound
- Please remove the Timebar/below dark BG colour space on the desktop, so the video is visible a little higher.
- Desktop: Make the video height match the container and the width is automatic. So its screen filling.

**Comment by Nicolasunikbase** [comment]
- it should not be a video player, but rather a video natively embedded within the website :)
- Cut the video at 1:08 (or 1:12min)
- Loop the video
- Remove the timebar
- Should be muted by default, yet with a sound ON obvious enough switch (large)
- The video should match the height of the container and the width is automatic. So its screen filling.
- Blue curtain should cover 80% of the video when page opens
THANKS!
