### ISSUE TITLE
[Enhancement] Create a vimeo account for Unikbase and use it for storing website resources.

### ISSUE THREAD

**Issue by ryansagot** [unikbase/website#34]
<table dir="ltr" style="height: 538px;" border="1" cellspacing="0" cellpadding="0"><colgroup><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /><col width="100" /></colgroup>
<tbody>
<tr><td><b/>CURRENT BEHAVIOR</td><td>Videos are stored in Nguyen Hung's vimeo account. When the video ends, it displays "More from nguyen hung"
<img width="976" alt="Screenshot 2023-02-27 at 11 15 56 AM" src="https://user-images.githubusercontent.com/116533751/221465245-77f242e5-2efa-43b0-8c6c-214be8dbe898.png">
</td></tr>
<tr><td><b/>GOAL/REQUEST</td><td>Create a vimeo account for Unikbase and dedicate it to storing the website's resources.</td></tr>
</tbody>
</table>

**Comment by rambuvn** [comment]
Changed

**Comment by ryansagot** [comment]
QA Passed using the March 30, 2023 version of the web app.
