### ISSUE TITLE
main video at the top of the homepage cuts before it reaches the end

### ISSUE THREAD

**Issue by Nicolasunikbase** [unikbase/website#39]
the end is: fade out to blue, unlocking collectibles, Unikbase logo fade to black

**Comment by Nicolasunikbase** [comment]
this is the link to the right video to use :
https://f.io/pVn9Fv9t
@rambuvn @smichea

**Comment by Nicolasunikbase** [comment]
Hi @rambuvn @ryansagot @smichea , when do you think will you update the video? thanks!

**Comment by rambuvn** [comment]
@Nicolasunikbase @ryansagot i replaced with new video please check

**Comment by ryansagot** [comment]
QA Passed using the March 28, 2023 version of the website.
