### ISSUE TITLE
Add an image in the meta data that will appear when sharing URL

### ISSUE THREAD

**Issue by Nicolasunikbase** [unikbase/website#40]
right now there is no image displayed (cf screenshot).

<img width="465" alt="Screenshot 2023-03-15 at 17 37 40" src="https://user-images.githubusercontent.com/122465123/225378639-c1746048-448e-4c56-8f2d-6a5529564dc3.png">

I'm adding the image which should appear:
<img width="440" alt="unikbase-logo-tagline-colour-negative-FAW" src="https://user-images.githubusercontent.com/122465123/225379081-532a6253-9189-4fa6-8e78-5ec2bf02d409.png">

**Comment by rambuvn** [comment]
![image](https://user-images.githubusercontent.com/1720202/225527875-d2f830fb-0850-430e-8851-5c9af92c3ae5.png)
Updated, look like the image blurry a bit, can you provide another image with ratio is 1.9 w/h please

**Comment by ryansagot** [comment]
Hi @rambuvn I am reopening this ticket as the image is not completely displayed in mobile.
![1678980158720](https://user-images.githubusercontent.com/116533751/225664914-eee6fe88-05b7-484e-8c83-72546995af91.jpg)

**Comment by rambuvn** [comment]
@ryansagot I checked and it will show fully on feed

**Comment by ryansagot** [comment]
QA Passed using April 3, 2023 version of the web app.
