### ISSUE TITLE
Thumbnail display when share website link 

### ISSUE THREAD

**Issue by rambuvn** [unikbase/website#44]

**Comment by rambuvn** [comment]
LinkedIn
<img width="335" alt="image" src="https://github.com/unikbase/website/assets/1720202/3b8b3779-95b8-448c-882e-b6828bd4525e">
Whatsapp
<img width="258" alt="image" src="https://github.com/unikbase/website/assets/1720202/5819732d-3352-4457-8400-0974f6c60494">

@Nicolasunikbase @johncalado @ryansagot  I have updated the thumbnail issue on whatsapp, linkedin, work for https://. The problem related to www. link i guest it is base on app which is desire to load or not with text start by www.

**Comment by ryansagot** [comment]
QA Passed using the July 13, 2023 version of the webapp. Tested on iMessage, Messenger, and Whatsapp.
