### ISSUE TITLE
Footer: Add Instagram carrousel on the homepage

### ISSUE THREAD

**Issue by Nicolasunikbase** [unikbase/website#5]
Create an instagram carousel section above the blog section
carousel should be swipable left or right

If you want to use a widget here is the style I'd like us to use: https://embedsocial.com/p/templates/instagram-carousel-widget
please contact me on skype if needed

Instagram access codes (pls do not share)

login : ****

password : *****

**Comment by CharlotteDeDeyne** [comment]
Add Instagram Feed to footer > See visual
<img width="714" alt="Instagram-Footer" src="https://user-images.githubusercontent.com/123545031/215126092-90b16219-5806-464c-9b37-9be9a4af1c8c.png">
