### ISSUE TITLE
Translations: French version of the Corporate website, Collector Website, Onboarding site

### ISSUE THREAD

**Issue by Nicolasunikbase** [unikbase/website#6]
Translations are available here:
https://docs.google.com/document/d/1ypevUfqLIdltKGBPpSwbUWE3U9dOk0O4uC8U4EzUzJk/edit
https://www.notion.so/unikbase/Plans-prices-landing-page-2dd7f4fd32414e6ea0c957a6e70621cf

**Comment by Nicolasunikbase** [comment]
when is the release of the French version due please?

**Comment by Nicolasunikbase** [comment]
Hi all
@CharlotteDeDeyne  is preparing a Figma file to help you positioning the French translations
please do not wait for all files to be uploaded on Sigma to start implementing the French pages

**Comment by smichea** [comment]
To be check because some translations where missing.
How should we translate "Unlock your collectibles" ?

**Comment by CharlotteDeDeyne** [comment]
[website-homepage-translation.pdf](https://github.com/unikbase/website/files/10741867/website-homepage-translation.pdf)

**Comment by ryansagot** [comment]
QA Passed as of 02/22/23
