### ISSUE TITLE
Desktop Website: Add a EN / FR switch to move from English to French language

### ISSUE THREAD

**Issue by Nicolasunikbase** [unikbase/website#7]
please refer to screenshiot

![Screenshot 2023-01-26 at 16 07 13](https://user-images.githubusercontent.com/122465123/214871363-778a1785-919d-402e-a0d0-9535275c1ea2.png)

**Comment by CharlotteDeDeyne** [comment]
<img width="809" alt="HomepageHeader-SignIn-Language" src="https://user-images.githubusercontent.com/123545031/215124997-ee019a3e-652e-4edd-90cc-b9f57020399a.png">
<img width="1048" alt="Language Hover" src="https://user-images.githubusercontent.com/123545031/215125501-54bdf363-7408-40e8-9e40-cfd63c0a04d9.png">
