### ISSUE TITLE
Desktop Website: 'Sign in'

### ISSUE THREAD

**Issue by Nicolasunikbase** [unikbase/website#8]
please refer to the screenshot
only show "sign in" and when clicking there should be 2 options (operator or collector)
![Screenshot 2023-01-26 at 16 09 24](https://user-images.githubusercontent.com/122465123/214871912-3130fc75-e5e1-4fb9-821c-853b238fe0f6.png)

**Comment by CharlotteDeDeyne** [comment]
<img width="809" alt="HomepageHeader-SignIn-Language" src="https://user-images.githubusercontent.com/123545031/215124822-a946b812-d0ff-4ce7-ada7-ad7c172a6ac2.png">
<img width="1046" alt="SignIn Hover" src="https://user-images.githubusercontent.com/123545031/215125630-f8c7bebe-6759-4b8d-b03e-d756925e700f.png">
